### ISSUE TITLE
Tooltip showing incorrect time

### ISSUE THREAD

**Issue by angelotodaro** [lbell/pretty-google-calendar#1]
It looks like the tooltip is showing the incorrect time by a few hours. It even shows that in the screenshot in the documentation. If you can direct to where that part of the code is I can look to see if I can fix it myself.

**Comment by angelotodaro** [comment]
It looks like it is actually showing the UTC time on the tooltip rather than the event time using the chosen time zone.

**Comment by lbell** [comment]
Fixed in v1.2.0
