### ISSUE TITLE
Colors for Multiple Calendars

### ISSUE THREAD

**Issue by lbell** [lbell/pretty-google-calendar#18]
Color multiple calendars differently.

FullCalendar Docs: https://fullcalendar.io/docs/event-source-object

**Comment by lbell** [comment]
V6 allows classname in GCal args. Parse the calendar name for css?

**Comment by lbell** [comment]
While we added the ability to color separate calendars on the page differently, we still need to color separate calendar feeds within the same calendar differently. See: https://github.com/lbell/pretty-google-calendar/pull/31

**Comment by lbell** [comment]
Added in v1.7.0

**Comment by lbell** [comment]
Added in v1.7.0

**Comment by BertCurbit** [comment]
Works like a charm! Thanks for this
