### ISSUE TITLE
Translation / Localization

### ISSUE THREAD

**Issue by rbornhauser** [lbell/pretty-google-calendar#2]
Hi,

I really like the plugin. Simple and good design and very easy to use.

Would it be possible to add a translation and localization-features for different time-formats?
I would of course help with the translation (German and French)

**Comment by lbell** [comment]
Howdy! Added basic locale support in v1.3.0. It adds a shortcode argument: `locale="fr"` etc.

Adding translations to the rest of the plugin will take some time.

**Comment by lbell** [comment]
Improved locale settings. Note if you use `list_type="month"` the button label will update automatically. However if you want to keep it at the current default of showing the next 28 days, you can customize the list button using `custom_list_button="Your label"` in the shortcode.

**Comment by lbell** [comment]
- [ ] Add localization to plugin front-end (map, add to google calendar buttons etc)
- [ ] Add localization to plugin back-end

**Comment by lbell** [comment]
@mwguerra Folded these changes in, but updated the text-domain to the full plugin slug as required by Wordpress. However, the translate page says it still isn't ready: https://translate.wordpress.org/projects/wp-plugins/pretty-google-calendar/

If you have any ideas how to fix, I'd be much obliged. Thanks!

**Comment by mwguerra** [comment]
It is ready and I’ve already translated it to Portuguese (Brazil)! :-)

**Comment by lbell** [comment]
Excellent! Must have just needed some time to update. Thanks again for all the help with this!
