### ISSUE TITLE
Don't restrict initial_view option

### ISSUE THREAD

**Issue by jacobmc** [lbell/pretty-google-calendar#20]
Hey there! I would love to use this plugin but my client really wants a week view. It would also be great if you could set the default view manually.

**Comment by lbell** [comment]
Howdy! Try using `views="dayGridMonth, dayGridWeek"` or `views="dayGridMonth, timeGridWeek"`

I agree the `initial_view` option seems unnecessarily restrictive at this moment. I'll work on making that more permissive.

(Currently in initial view is restricted to: dayGridMonth, listDay, listWeek, listMonth, listYear, listCustom)

**Comment by lbell** [comment]
In the meantime, you can modify helpers.js line [32-36](https://github.com/lbell/pretty-google-calendar/blob/129ca27bb36383a472d34e4bcd820f9c21e1e049/public/js/helpers.js#L32) to look like:

```
  //   let initialView = "dayGridMonth";

  //   if (allowedViews.includes(settings["initial_view"])) {
  //     initialView = settings["initial_view"];
  //   }

  let initialView = settings["initial_view"];
```

That should allow you to set `initial_view="timeGridWeek"`

**Comment by mwguerra** [comment]
Actually, there is! 

<img width="836" alt="image" src="https://user-images.githubusercontent.com/27717982/230427287-16940ac0-3f6d-4366-aeae-73e453ce561b.png">

Just use the shortcode attribute initial_view, setting it to a view defined in the views attribute. 

The line:

https://github.com/lbell/pretty-google-calendar/blob/129ca27bb36383a472d34e4bcd820f9c21e1e049/public/js/helpers.js#L27

defines the views available. Any other available at Full Calendar can be used too, but I can't say for sure the CSS for them are ok or not. This will need some more testing to incllude it in the allowed views.

Hope this helps in anyway!

**Comment by NurDerFCN** [comment]
Hello,

support of "dayGridWeek" or "timeGridWeek" in initial_view would be really great.
