### ISSUE TITLE
Adding use instructions to settings page

### ISSUE THREAD

**Issue by jhanten** [lbell/pretty-google-calendar#22]
Please consider copying all the instruction content from the plugin description to be included in the settings page for easier access. You include the default shortcode, but I can’t think of any reason not to include all the other options on this page with perhaps a second tab for instructions. I think it would make your plugin much easier to use. Thank you for your consideration.

**Comment by lbell** [comment]
Hoping to simplify the whole process soon.

The only reason to NOT include it there, is the desire to have one universal source of truth (the docs) rather than updating changes in several different places.

But I get your point.

Thanks!

**Comment by lbell** [comment]
Added a link to the docs on the settings page :-)
