### ISSUE TITLE
Add ability to have more than one distinct calendar shortcode on a page

### ISSUE THREAD

**Issue by jhanten** [lbell/pretty-google-calendar#23]
Is there a way to use your shortcode more than one time on a page?  It appears to only load the first when used this way.

**Comment by lbell** [comment]
It appears that this isn't currently possible. Will add to the wish-list. Thanks!

**Comment by roaldschaap** [comment]
Hi,

I have this feature request as well.
Is there any info on when this item from the wish-list is going to be built?

(We would like to add 3 different calenders (shortcodes) on the same page. all in a tab.)

**Comment by lbell** [comment]
Looking into this... When exactly is the trick. I do this in my spare time, and there's not much of that as I have to pay the bills ;-).

**Comment by clickresults-za** [comment]
How can we make this happen?

Really need this feature.

**Comment by lbell** [comment]
@roaldschaap & @clickresults-za & @jhanten 

Can you install the multical branch: https://github.com/lbell/pretty-google-calendar/tree/multical and see if that does what you need?

Want some testing before I release it into the wild...

**Comment by roaldschaap** [comment]
Thanks,

I can test this monday,

**Comment by clickresults-za** [comment]
Tested on a staging server, and it looks good.

Will give it a go on a production site.

**Comment by roaldschaap** [comment]
Yes, it works!

tested it with 2 different calendars in tabs in elementor. Works great!


Roald

Roald  Schaap

Art director

Kitemedia
+31 - 30 23 78 131 <+31302378131> | +31 - 6 28 337 994 <+31628337994>
***@***.***
kitemedia.nl
Janskerkhof 28, 3512 BN, Utrecht




Op vr 22 sep 2023 om 12:02 schreef clickresults-za ***@***.***
