### ISSUE TITLE
Event times

### ISSUE THREAD

**Issue by andrewcocluff** [lbell/pretty-google-calendar#24]
In the detailed event information that pops up on click, only the start time is displayed and it is formatted to show hours minutes and seconds. Times in Google Calendar are entered as hours and minutes, having two extra zeros on the end for seconds looks strange.

May I also suggest adding the finish time and the location (just the text description which might be the name of a meeting room or a building or "on Zoom" etc.  Listing the start and finish times and the location seems to be a standard practice across all other WP Calendar plugins so I expect it would be something most people would want. I am sending a picture showing an example entry how it is now and how I think it should look.

Thanks for creating pretty calendar, it is by far the best looking of all the calendar plugins that I have tested :-)

![Pretty Calendar Suggestion](https://github.com/lbell/pretty-google-calendar/assets/136352863/c52a539a-9dc6-4770-9e75-cd4315cf9742)

**Comment by lbell** [comment]
Think we got your laundry list. Great ideas!
