### ISSUE TITLE
Display N number of events in list view

### ISSUE THREAD

**Issue by concierge-en-ligne** [lbell/pretty-google-calendar#25]
Hi Loren,

Fabulous plugin. I use it to support the school of my son. Thanks to your work, all parents now have a great-looking calendar for the public school events.

I have one question about the list view. Instead of limiting the view based on a time range, I'd like to limit it to a specific number of events. This would greatly help with the balance of the site design. I looked at the [fullcalendar.io documentation page](https://fullcalendar.io/docs#toc) but I can't seem to find that option. I was hoping to find a parameter in the lines of "list_view_max_limit=12".

Have I missed the documentation for this ?

Thanks
Greg

**Comment by lbell** [comment]
Yeah... I don't think this is possible with FullCalendar. Sorry.
