### ISSUE TITLE
Sub-par handling of large amounts of information in tooltip

### ISSUE THREAD

**Issue by lbell** [lbell/pretty-google-calendar#3]
From: https://wordpress.org/support/topic/days-list-support/#post-15650562

When an event title is clicked on and the popup is being displayed, any events with lots of content—maybe more than a screen height’s worth of text in the event Description section, for example—the popup will push off to the left of the theme content and is not fully visible to the user.

I was able to use some CSS to move some divs back to the center of the page (id tippy-1 and tippy-2). But this only works when you actually know the id of the “tippy-[id]” div.

https://prnt.sc/nHDxmSILB8q3

**Comment by tradesouthwest** [comment]
**Verified** that pretty cal opens popup off page on other themes. Test two default WP themes and “Editorial” and “StoreFront.” http://tswdev.com/test/test-layout-page/ (Editorial theme).

**Comment by admin242424** [comment]
Hello, I also have this problem with the tooltip opening off screen on desktop.  Is there a way to disable the data-placement "left" and "right" calculations altogether?  CSS hacks I'm trying all end up looking a little wonky.  Thank you for the awesome plugin overall!

**Comment by lbell** [comment]
After digging into this deeper a fix is outside our scope and likely won't happen.
