### ISSUE TITLE
use_tooltip and no_link not working

### ISSUE THREAD

**Issue by beehoover** [lbell/pretty-google-calendar#38]
Hello, 

Thank you for developing this free and easy to use plug-in. The setup was very easy, however I despite setting use_tooltip="true" no_link="true", event details do not show when cursor hovers over event, and the event it clicked, google calendar is opened in a new tab. 

[pretty_google_calendar gcal= "stthomaschurcheugene@gmail.com" use_tooltip="true" no_link="true" enforce_listview_on_mobile="true" show_today_button="true" ]

https://st-thomaseugene.net/church-calendar/

Thank you!

**Comment by lbell** [comment]
Looks like this has been resolved.
