### ISSUE TITLE
Controls not visible

### ISSUE THREAD

**Issue by alankley** [lbell/pretty-google-calendar#54]
<img width="758" alt="PrettyCalendarIsue" src="https://github.com/user-attachments/assets/9fb6e7db-1caf-48a5-8d26-63d384ed897e">

Embeded in Pinbin theme results in not being able to see controls at the top

**Comment by lbell** [comment]
Odd - can you share a link?

**Comment by lbell** [comment]
Actually, looking at the pic again in this light, I can see the labels in very faint white, which leads me to believe this is a CSS issue.
