### ISSUE TITLE
Suggestion: Avoid loading external scripts on the front-end (better privacy, GDPR compliance)

### ISSUE THREAD

**Issue by svtcpx** [lbell/pretty-google-calendar#55]
Hi there,

this plugin works really well for me but I wish there was a way to avoid loading content from Google servers on the front-end as that always introduces an "issue" with privacy, repectively GDPR compliance. There are some countries (Germany for example) where the use of any such scripts is still somewhat of a grey area, even after obtaining a Google-signed agreement.

At any rate, I just thought I’d spark the idea, maybe there’s some desire to look into it. Proxying these requests would certainly add to the value of the plugin as far as I am concerned and from what I can tell, give it a unique feature among the other plugins of the kind.

All the Best

**Comment by lbell** [comment]
Howdy! 

Which scripts do you see being loaded from Google servers? 

This plugin only loads things locally, however FullCalendar might be reaching out to external scripts. If that's the case, then that's probably outside our control.

**Comment by svtcpx** [comment]
I don't know what "FullCalendar" refers to but I'm seeing the script being loaded in both the month and list views:

`
https://www.googleapis.com/calendar/v3/calendars/MY@MAIL/events?key=REDACTED&timeMin=2024-10-27T00%3A00%3A00.000Z&timeMax=2024-12-03T00%3A00%3A00.000Z&singleEvents=true&maxResults=9999&timeZone=undefined`

Initiator: index.global.min.js?ver=2.0.0:6

Let me know if I can do something to help "debug" this further.

Edit: I see what you mean by FullCalendar now.

**Comment by lbell** [comment]
Confirming this is called by FullCalendar's Google Calendar extension: https://fullcalendar.io/docs/google-calendar and is outside of our control. Sorry!
