### ISSUE TITLE
Accept multiple calendars

### ISSUE THREAD

**Issue by lbell** [lbell/pretty-google-calendar#9]
Requested here: https://wordpress.org/support/topic/multiple-calendars-41/

Supported here: https://fullcalendar.io/docs/v3/google-calendar

Should be straightforward to implement when I have time.

**Comment by dsumms** [comment]
Hoping that I could help support a fellow freelancer. I saw that we both live in NM and had to leave a comment.

**Comment by lbell** [comment]
Thanks @dsumms! Hoping to have some time this fall/winter to implement some of these good ideas.

**Comment by lbell** [comment]
Added with c11dc6c7cbfbdda54d1173e85a78455e919445ab
